# Snakefile

# Include the configfile:
configfile: "config.yaml"

# Include the rule for modifying VCFs
include: "rules/modify_vcf.smk"
include: "rules/vcf_Fst.smk"
include: "rules/plot_Fst.smk"

# Final output rule:
rule all:
    input:
        rules.plot_Fst.output